# Generated by Django 3.0.5 on 2020-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
