# Generated by Django 3.0.5 on 2020-06-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200621_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
