# Generated by Django 3.0.5 on 2020-05-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
