# Generated by Django 3.0.5 on 2020-05-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='descuento',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='producto',
            new_name='product',
        ),
    ]
