# Generated by Django 3.0.5 on 2020-06-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200614_1544'),
        ('market', '0006_remove_orden_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='UserProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
