# Generated by Django 3.0.5 on 2020-06-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200614_1544'),
        ('market', '0007_auto_20200617_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
